### ISSUE TITLE
Expose API for configured/exising Environments

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#17] opened 2015-01-22 22:28 UTC
Uncertain what depth of information the API should expose, but an API consumer should at the very least be able to get a list of Environments.

At a bare minimum something like this:

```json
[
  {
    "name" : "production"
  },
  {
    "name" : "stage-1"
  }
]
```

**Comment by maheshkelkar** [comment] 2015-02-25 14:18
Fixed (duplicate of #59)

**Closed by maheshkelkar** 2015-02-25 14:18 UTC
Labels: api
