### ISSUE TITLE
Invalid JSON in cucumber tests doesn't properly raise exceptions

### ISSUE THREAD

**Issue by rtyler** [lookout/deploydb#26] opened 2015-02-05 22:33 UTC
When @maheshkelkar was writing some tests, he had a trailing comma and that caused the cucumber tests to be green despite the fact that the client was PUTing invalid JSON to the server

**Comment by maheshkelkar** [comment] 2015-02-07 00:50
To reproduce take out @NotEmpty attribute out of Artifact.groovey (for either version or sourceUrl) and run the cucumber tests. 

The test should fail due to internal error - 500. 

If you add a "comma" at the end of last row in JSON format in artifact/creating.feature, 
e.g. last row is "sourceUrl" = ...
  @error 
  Scenario: The request should fail when creating an Artifact without a version

    When I PUT to "/api/v1/artifacts" with:
    """
      {
        "group" : "com.example.cucumber",
        "name" : "cukes",
        "sourceUrl" : "http://example.com/cucumber.jar",
      }
    """
    Then the response should be 422

the test returns 400 (which was considered as PASS in the past)

**Comment by rtyler** [comment] 2015-02-07 16:19
@maheshkelkar does this mean we should close this issue out then since we've changed the expectation of the response code to be 422? 400 (Bad Request) is the appropriate error code for malformed JSON

**Comment by maheshkelkar** [comment] 2015-02-08 23:43
@tyler 

This seems like a bugs somewhere in putJsonToPath function. That seems like out of scope of deployDb, hence we can close it and perhaps create an issue for dropwizard?

So, I guess we can close this one.

**Comment by rtyler** [comment] 2015-02-09 15:53
@maheshkelkar the `putJsonToPath` function is in "our" code anyways in `src/cucumber` but that method doesn't _parse_ the JSOn it only passes the string along to the server to parse. If the server-siude parsing of the JSON is properly returning a 422 on malformed JSON, then this issue can be closed

**Comment by maheshkelkar** [comment] 2015-03-12 15:09
I confirmed that this in NOT an error in our code. 400 is generated for the malformed JSON

**Closed by maheshkelkar** 2015-03-12 15:09 UTC
Labels: bug
